version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: xsm-postgres
    environment:
      POSTGRES_DB: xsm_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - xsm-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U xsm_user -d xsm_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build: .
    container_name: xsm-server
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: "5432"
      DB_USER: postgres
      DB_PASSWORD: 1111
      DB_NAME: xsm_db
    ports:
      - "8080:8080"
    networks:
      - xsm-network
    restart: unless-stopped

networks:
  xsm-network:
    driver: bridge

volumes:
  postgres_data: